name: Deploy to TestFlight

on:
  workflow_dispatch:
    inputs:
      changelog:
        description: 'Notes de version'
        required: false
        default: 'Nouvelles fonctionnalités et corrections'

jobs:
  deploy:
    runs-on: macos-latest
    timeout-minutes: 60

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
          bundler-cache: true

      - name: Write App Store Connect API Key
        env:
          ASCAPI_KEY_CONTENT: ${{ secrets.ASCAPI_KEY_CONTENT }}
        run: |
          mkdir -p ~/.appstoreconnect/private_keys
          echo "$ASCAPI_KEY_CONTENT" > ~/.appstoreconnect/private_keys/AuthKey_${{ secrets.ASCAPI_KEY_ID }}.p8

      - name: Deploy to TestFlight
        env:
          ASCAPI_KEY_ID: ${{ secrets.ASCAPI_KEY_ID }}
          ASCAPI_ISSUER_ID: ${{ secrets.ASCAPI_ISSUER_ID }}
          ASCAPI_KEY_FILEPATH: ${{ format('{0}/.appstoreconnect/private_keys/AuthKey_{1}.p8', env.HOME, secrets.ASCAPI_KEY_ID) }}
        run: bundle exec fastlane beta changelog:"${{ github.event.inputs.changelog }}"
